app:
  name: example
  host: localhost
  port: 8080
  secret_key: secret
auth:
  expiration_refresh_token_in_days: 30
  expiration_access_token_in_minutes: 30
relation_database:
  connection:
    master: sqlite
    master_orm: gorm
    slave: sqlite
    slave_orm: gorm
    test: sqlite
  connections:
    sqlite:
      master_dsn: "file:local.sqlite"
      slave_dsn: "file:local.sqlite?mode=ro"
      test_dsn: "file::memory:?cache=shared"
