app:
  host: localhost
  port: 8080
relation_database:
  connection:
    master: sqlite
    master_orm: gorm
    slave: sqlite
    slave_orm: gorm
    test: sqlite
  connections:
    sqlite:
      master_dsn: "file:local.sqlite"
      slave_dsn: "file:local.sqlite?mode=ro"
      test_dsn: "file::memory:?cache=shared"
